from mataki._client import AsyncMataki, Mataki
from mataki._errors import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConnectionError,
    InternalServerError,
    MatakiError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
)
from mataki._version import __version__
from mataki.types import (
    Ad,
    AdAnnotations,
    AdFormat,
    AdStatus,
    AdType,
    Advertiser,
    AdvertiserAnnotations,
    AdvertiserStatus,
    Annotations,
    ApiKey,
    ApiKeyAnnotations,
    Audit,
    BidderType,
    Campaign,
    CampaignAnnotations,
    CampaignStatus,
    CreateApiKeyResponse,
    Environment,
    LineItem,
    LineItemAnnotations,
    LineItemStatus,
    OffsetPaginationMeta,
    Organization,
    OrganizationAnnotations,
    Placement,
    PlacementAnnotations,
    Role,
)

__all__ = [
    # Clients
    "AsyncMataki",
    "Mataki",
    # Version
    "__version__",
    # Errors
    "APIError",
    "AuthenticationError",
    "BadRequestError",
    "ConnectionError",
    "InternalServerError",
    "MatakiError",
    "NotFoundError",
    "PermissionDeniedError",
    "RateLimitError",
    # Types
    "Ad",
    "AdAnnotations",
    "AdFormat",
    "AdStatus",
    "AdType",
    "Advertiser",
    "AdvertiserAnnotations",
    "AdvertiserStatus",
    "Annotations",
    "ApiKey",
    "ApiKeyAnnotations",
    "Audit",
    "BidderType",
    "Campaign",
    "CampaignAnnotations",
    "CampaignStatus",
    "CreateApiKeyResponse",
    "Environment",
    "LineItem",
    "LineItemAnnotations",
    "LineItemStatus",
    "OffsetPaginationMeta",
    "Organization",
    "OrganizationAnnotations",
    "Placement",
    "PlacementAnnotations",
    "Role",
]
